Provider: Yaml
MySql:
  Host: "127.0.0.1"
  Port: "3306"
  User: "root"
  Database: "reportsystem"
  Password: "japanese_goblin"
MongoDB:
  Uri: "URI_LINK"
  Database: "reportsystem"

Commands:
  Report: "report"
  ReportDescription: "Report a bad player"
  Reportmanager: "reportmanager"
  ReportmanagerDescription: "Manage reports in an UI"
  Myreports: "myreports"
  MyreportsDescription: "Show all your reports"

ConfigVersion: 1