name: ReportSystemNK
version: 2.2.0-SNAPSHOT
api: 1.0.0
author: Mundschutziii
main: net.llamadevelopment.reportsystem.ReportSystem
description: Report bad players and manage as staff member the reports